In [1]:
import csv 
import pandas as pd 
import numpy as np
import requests

In [2]:
url = 'https://raw.githubusercontent.com/shaelm/Toronto-Transit-Commision-Delay-Mining/master/datasets/weatherstats_toronto_daily.csv'
df = pd.read_csv(url,sep=",")

In [3]:
df

date  max_temperature  ...  avg_cloud_cover_10  min_cloud_cover_10
0     2019-11-10              7.4  ...                 NaN                 NaN
1     2019-11-09              3.3  ...                 NaN                 NaN
2     2019-11-08              0.6  ...                 NaN                 NaN
3     2019-11-07              2.6  ...                 NaN                 NaN
4     2019-11-06              5.2  ...                 NaN                 NaN
...          ...              ...  ...                 ...                 ...
2495  2013-01-10              6.3  ...                 0.0                 0.0
2496  2013-01-09              6.4  ...                 0.5                 0.0
2497  2013-01-08              2.7  ...                 0.0                 0.0
2498  2013-01-07              0.8  ...                 0.5                 0.0
2499  2013-01-06              2.1  ...                 0.5                 0.0

[2500 rows x 70 columns]

In [4]:
## Nan count in each column'
df.isnull().sum()

date                            0
max_temperature                 0
avg_hourly_temperature          0
avg_temperature                 0
min_temperature                 0
                             ... 
min_cloud_cover_8             276
max_cloud_cover_10           2341
avg_hourly_cloud_cover_10    2341
avg_cloud_cover_10           2341
min_cloud_cover_10           2341
Length: 70, dtype: int64

In [5]:
## dropping column with Nan values in them  
newdf = df.copy()
for i in newdf.columns:
  if newdf[i].isnull().sum() > 100:
    newdf.drop(columns=[i], inplace=True)

In [6]:
newdf

date  max_temperature  ...  rain  snow
0     2019-11-10              7.4  ...   0.4   0.2
1     2019-11-09              3.3  ...   0.0   0.0
2     2019-11-08              0.6  ...   0.0   0.0
3     2019-11-07              2.6  ...   1.6   2.0
4     2019-11-06              5.2  ...   0.2   0.4
...          ...              ...  ...   ...   ...
2495  2013-01-10              6.3  ...   0.0   0.0
2496  2013-01-09              6.4  ...   0.0   0.0
2497  2013-01-08              2.7  ...   0.0   0.0
2498  2013-01-07              0.8  ...   0.0   0.0
2499  2013-01-06              2.1  ...   0.0   0.2

[2500 rows x 41 columns]

In [7]:
## dropping columns with no variation (same value)

for i in newdf.columns:
  if len(newdf[i].unique()) == 2:
    newdf.drop(columns=[i], inplace=True)

In [8]:
newdf.head()

date  max_temperature  ...  rain  snow
0  2019-11-10              7.4  ...   0.4   0.2
1  2019-11-09              3.3  ...   0.0   0.0
2  2019-11-08              0.6  ...   0.0   0.0
3  2019-11-07              2.6  ...   1.6   2.0
4  2019-11-06              5.2  ...   0.2   0.4

[5 rows x 41 columns]

In [9]:
newdf.dtypes

date                             object
max_temperature                 float64
avg_hourly_temperature          float64
avg_temperature                 float64
min_temperature                 float64
max_relative_humidity             int64
avg_hourly_relative_humidity    float64
avg_relative_humidity           float64
min_relative_humidity             int64
max_dew_point                   float64
avg_hourly_dew_point            float64
avg_dew_point                   float64
min_dew_point                   float64
max_wind_speed                    int64
avg_hourly_wind_speed           float64
avg_wind_speed                  float64
min_wind_speed                    int64
max_pressure_sea                float64
avg_hourly_pressure_sea         float64
avg_pressure_sea                float64
min_pressure_sea                float64
max_pressure_station            float64
avg_hourly_pressure_station     float64
avg_pressure_station            float64
min_pressure_station            float64


#### for the second section of this notebook i will be using the data at hand to predict if the next day will rain or not. first we convert rain to a binary variable (yes, no), second we will create a new column called rain_tomorrow, this column will be a (yes, no) column aswell inicating if there will be rain the next day 

In [10]:
## first lets fill messing values with mods (most freaquent value in each column)
newdf = newdf.fillna(newdf.mode().iloc[0])

In [11]:
newdf

date  max_temperature  ...  rain  snow
0     2019-11-10              7.4  ...   0.4   0.2
1     2019-11-09              3.3  ...   0.0   0.0
2     2019-11-08              0.6  ...   0.0   0.0
3     2019-11-07              2.6  ...   1.6   2.0
4     2019-11-06              5.2  ...   0.2   0.4
...          ...              ...  ...   ...   ...
2495  2013-01-10              6.3  ...   0.0   0.0
2496  2013-01-09              6.4  ...   0.0   0.0
2497  2013-01-08              2.7  ...   0.0   0.0
2498  2013-01-07              0.8  ...   0.0   0.0
2499  2013-01-06              2.1  ...   0.0   0.2

[2500 rows x 41 columns]

In [12]:
## converting rain to 1/0 categorical column (1 means rain, 0 means no rain)

newdf['rain'] = (newdf['rain'].values > 0.0)

In [13]:
newdf['rain'] = newdf['rain'].apply(lambda x: 1 if x == True else 0)

In [14]:
newdf['rain']

0       1
1       0
2       0
3       1
4       1
       ..
2495    0
2496    0
2497    0
2498    0
2499    0
Name: rain, Length: 2500, dtype: int64

In [15]:
newdf['rain_tomorrow'] = newdf['rain'].shift(1)

In [21]:
newdf['rain_tomorrow'][0] = 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [22]:
newdf

max_temperature  avg_hourly_temperature  ...  month  day
0                 7.4                    3.41  ...     11   10
1                 3.3                    0.76  ...     11    9
2                 0.6                   -3.00  ...     11    8
3                 2.6                   -0.09  ...     11    7
4                 5.2                    1.78  ...     11    6
...               ...                     ...  ...    ...  ...
2495              6.3                    2.85  ...      1   10
2496              6.4                    3.40  ...      1    9
2497              2.7                    0.35  ...      1    8
2498              0.8                   -3.15  ...      1    7
2499              2.1                    0.67  ...      1    6

[2500 rows x 44 columns]

In [18]:
## spliting the date column into (year month day) separate columns
newdf['date'] = pd.to_datetime(df['date'])
newdf['year'] = newdf['date'].dt.year.astype('int')
newdf['month'] = newdf['date'].dt.month.astype('int')
newdf['day'] = newdf['date'].dt.day.astype('int')

In [19]:
newdf.drop(['date'], 1, inplace=True)

In [20]:
cols = list(newdf.columns)
cols.remove('rain_tomorrow')

#### now we have our target, let's build a machine learning model to predict if there will be rain the next day

**data preparation**

In [23]:
from sklearn.model_selection import train_test_split
X = newdf.drop(['rain_tomorrow'], 1)
y = newdf['rain_tomorrow']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [24]:
X_train.shape, X_test.shape

((2000, 43), (500, 43))

In [25]:
### now we scaler the features of (normalize the data)
from sklearn.preprocessing import StandardScaler

enc = StandardScaler()
X_train = enc.fit_transform(X_train)
X_test = enc.transform(X_test)

In [26]:
X_train

array([[-1.66214347, -2.06054013, -1.98471058, ...,  1.54065995,
        -1.60428699,  1.38678441],
       [ 0.65937536,  0.49698626,  0.55704532, ..., -0.49187297,
         1.06334957, -0.98842745],
       [ 1.53847991,  1.14711185,  1.2651059 , ...,  1.54065995,
         1.06334957, -1.66705941],
       ...,
       [ 0.94956521,  0.99806759,  1.06085766, ...,  0.52439349,
         1.06334957, -0.87532212],
       [ 0.76179531,  0.92766018,  0.92015331, ...,  0.52439349,
         0.17413739,  1.38678441],
       [ 0.83861027,  0.59939705,  0.54342877, ..., -0.49187297,
        -0.41867074, -1.55395408]])

In [28]:
X_train = pd.DataFrame(X_train, columns=[cols])
X_test = pd.DataFrame(X_test, columns=[cols])
X_train.head()

max_temperature avg_hourly_temperature  ...     month       day
0       -1.662143              -2.060540  ... -1.604287  1.386784
1        0.659375               0.496986  ...  1.063350 -0.988427
2        1.538480               1.147112  ...  1.063350 -1.667059
3       -0.202659              -0.161369  ...  1.063350  1.612995
4       -0.270939              -0.326872  ... -1.604287  1.726100

[5 rows x 43 columns]

**Feature Importance**


  -in this section i will use XGboost to see the importance of features and rank them accordingly

In [36]:
from xgboost import XGBRegressor
xgb = XGBRegressor()
xgb.fit(X_train, y_train)
imp = pd.DataFrame(xgb.feature_importances_, columns=['Importance'], index=X_train.columns)
imp['col_names'] = imp.index
imp[imp['Importance'] == 0]

[02:12:48] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


Importance          col_names
heatdegdays            0.0     (heatdegdays,)
cooldegdays            0.0     (cooldegdays,)
growdegdays_5          0.0   (growdegdays_5,)
growdegdays_7          0.0   (growdegdays_7,)
growdegdays_10         0.0  (growdegdays_10,)

In [37]:
## dropping columns that have nostatistical significance on the target 
X_train.drop(['heatdegdays', 'cooldegdays', 'growdegdays_5', 'growdegdays_7', 'growdegdays_10'], axis=1, inplace=True)
X_test.drop(['heatdegdays', 'cooldegdays', 'growdegdays_5', 'growdegdays_7', 'growdegdays_10'], axis=1, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:3889: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)


In [39]:
X_train.head()

max_temperature avg_hourly_temperature  ...     month       day
0       -1.662143              -2.060540  ... -1.604287  1.386784
1        0.659375               0.496986  ...  1.063350 -0.988427
2        1.538480               1.147112  ...  1.063350 -1.667059
3       -0.202659              -0.161369  ...  1.063350  1.612995
4       -0.270939              -0.326872  ... -1.604287  1.726100

[5 rows x 38 columns]

**Logestic Regression Mode**

In [47]:
y_train = y_train.astype('int')
y_test = y_test.astype('int')

In [48]:
from sklearn.linear_model import LogisticRegression


log = LogisticRegression(solver='liblinear', random_state=0)
log.fit(X_train.values, y_train.values)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [49]:
### prediction results:
y_pred_test = log.predict(X_test)

In [53]:
### becuase logistice regression yield probability for each prediction we can get the indivdual probabilities 
### this line will show the probability for the first 10 prediction of not raining tomorrow
log.predict_proba(X_test)[:,0][:10] 

array([0.53479716, 0.78509158, 0.63690147, 0.52307637, 0.4649999 ,
       0.88879712, 0.68874762, 0.82839546, 0.72643845, 0.87292617])

In [54]:
### the accuracy of this model
from sklearn.metrics import accuracy_score
print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred_test)))

Model accuracy score: 0.7060


In [55]:
### now we will check for the accuracy of the model on the training set to see if our model is not overfitting 
y_pred_train = log.predict(X_train)
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Training-set accuracy score: 0.7035


In [56]:
print('Training set score: {:.4f}'.format(log.score(X_train, y_train)))
print('Test set score: {:.4f}'.format(log.score(X_test, y_test)))

Training set score: 0.7035
Test set score: 0.7060


In [57]:
### it looks like the model is not overfitting
### the model might be underfitting because the test and train set results are very similar
### i will try and use less regulization on the model to see if it fixes the problem 

In [64]:
log2 = LogisticRegression(C=2000, solver='liblinear', random_state=0)
log2.fit(X_train, y_train)

LogisticRegression(C=2000, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [65]:
print('Training set score: {:.4f}'.format(log2.score(X_train, y_train)))
print('Test set score: {:.4f}'.format(log2.score(X_test, y_test)))

Training set score: 0.7110
Test set score: 0.7040


In [66]:
### we can see that after using higher C the training set is has slightly higher accuracy.

**Confusion Matrix**

In [69]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_test)

print('Confusion matrix\n\n', cm)
print('\nTrue Positives(TP) = ', cm[0,0])
print('\nTrue Negatives(TN) = ', cm[1,1])
print('\nFalse Positives(FP) = ', cm[0,1])
print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[310  37]
 [110  43]]

True Positives(TP) =  310

True Negatives(TN) =  43

False Positives(FP) =  37

False Negatives(FN) =  110


**classificatoin metrics**

In [70]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       0.74      0.89      0.81       347
           1       0.54      0.28      0.37       153

    accuracy                           0.71       500
   macro avg       0.64      0.59      0.59       500
weighted avg       0.68      0.71      0.67       500



### XGBOOST CLASSIFIER 

we saw how logestic regression perfomerd on the data now lets see how well XGB will perform

In [71]:
import xgboost as xgb
params_xgb ={'n_estimators': 500,
            'max_depth': 16}
model_xgb = xgb.XGBClassifier(**params_xgb)
model_xgb.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=16,
              min_child_weight=1, missing=None, n_estimators=500, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [73]:
y_pred = model_xgb.predict(X_test)

In [75]:
accuracy = accuracy_score(y_test, y_pred)
print('XBG accuracy:', accuracy)

XBG accuracy: 0.698


In [76]:
print('Training set score: {:.4f}'.format(model_xgb.score(X_train, y_train)))
print('Test set score: {:.4f}'.format(model_xgb.score(X_test, y_test)))

Training set score: 1.0000
Test set score: 0.6980


In [77]:
### from the results above we can see that XGB is Overfitting the training set
### i will reduce the number of estimators and max depth 
params_xgb ={'n_estimators': 100,
            'max_depth': 8}
model_xgb = xgb.XGBClassifier(**params_xgb)
model_xgb.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=8,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [78]:
print('Training set score: {:.4f}'.format(model_xgb.score(X_train, y_train)))
print('Test set score: {:.4f}'.format(model_xgb.score(X_test, y_test)))

Training set score: 0.9990
Test set score: 0.7120


In [104]:
### we can see model improved quite alot on test set and is performing worse on training set. great, now we need to add more regulizatin
params_xgb ={'n_estimators': 10,
            'max_depth': 10,
            'alpha': 6,
            'gamma': 1}
model_xgb = xgb.XGBClassifier(**params_xgb)
model_xgb.fit(X_train, y_train)

XGBClassifier(alpha=6, base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=1,
              learning_rate=0.1, max_delta_step=0, max_depth=10,
              min_child_weight=1, missing=None, n_estimators=10, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [105]:
print('Training set score: {:.4f}'.format(model_xgb.score(X_train, y_train)))
print('Test set score: {:.4f}'.format(model_xgb.score(X_test, y_test)))

Training set score: 0.9480
Test set score: 0.6900


In [ ]:
### we can see by adding more regulization training accuracy is going down but test accuracy is not going up

In [106]:
cm = confusion_matrix(y_test, y_pred_test)

print('Confusion matrix\n\n', cm)
print('\nTrue Positives(TP) = ', cm[0,0])
print('\nTrue Negatives(TN) = ', cm[1,1])
print('\nFalse Positives(FP) = ', cm[0,1])
print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[310  37]
 [110  43]]

True Positives(TP) =  310

True Negatives(TN) =  43

False Positives(FP) =  37

False Negatives(FN) =  110


**Random Forrest**

In [122]:
from sklearn.ensemble import RandomForestClassifier

params_rf = {'max_depth': 10,
             'min_samples_leaf': 1,
             'min_samples_split': 2,
             'n_estimators': 40,
             'random_state': 12345}
rf = RandomForestClassifier(**params_rf)
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=10, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=40,
                       n_jobs=None, oob_score=False, random_state=12345,
                       verbose=0, warm_start=False)

In [123]:
print('Training set score: {:.4f}'.format(rf.score(X_train, y_train)))
print('Test set score: {:.4f}'.format(rf.score(X_test, y_test)))

Training set score: 0.9325
Test set score: 0.7160


In [125]:
y_pred_test = rf.predict(X_test)
cm = confusion_matrix(y_test, y_pred_test)

print('Confusion matrix\n\n', cm)
print('\nTrue Positives(TP) = ', cm[0,0])
print('\nTrue Negatives(TN) = ', cm[1,1])
print('\nFalse Positives(FP) = ', cm[0,1])
print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[310  37]
 [105  48]]

True Positives(TP) =  310

True Negatives(TN) =  48

False Positives(FP) =  37

False Negatives(FN) =  105


**Lgistic Regression with cross validation**

In [130]:
from sklearn.model_selection import cross_val_score
log_cross = LogisticRegression(solver='liblinear')
score = cross_val_score(log_cross, X_train, y_train, cv=5, scoring='accuracy')

In [133]:
score[0]

0.725

In [134]:
### we can see we increased the accuracy score abit with cross validation 